############################################
# Data Science Training
# Homework Assignment of Course 1 Session 1
############################################

# Problem 1: Basic Statistical Programming -------------------
# consider the following vector of random numbers drawn from a 
# normal distribution with mean 10 and standard deviation 2
x <- rnorm(100, mean = 10, sd = 5)

# (a) plot a histogram of x using hist()

# (b) compute the sum, mean, median, standard deviation, minimum and maximum values and quantiles of this vector

# (c) manually compute the mean using sum() and length()

# (d) check your computation of the mean, median, minimum, maximum, 2nd and 4th quartile against:
summary(x)

# (e) write a function that takes x as an input and returns the same output as summary(x)

# (f) This inserts 10 missing values at random into x.
x[sample.int(100L, 10L)] <- NA
x
?sample.int  # See the help page of this function, make sure you understand the code above

summary(x)  # see the output now

# (g) Modify your function in part (e) to also replicate this output

# (h) Add an argument 'na.rm' to your function, and modify your function so that it can produce both outputs of (e) and (g) depending on na.rm = TRUE or FALSE

# (i) Consider this dataset that comes with R
mtcars
View(mtcars)
# make sure you understand this code. Look up the individual functions i.e. ?t, ?sapply
summ <- t(sapply(mtcars, summary))
summ
# Examine 'summ'. What kind of object is it?, see the structure and class of it

# (j) apply your function to each column of the data in the same way as shown above. Do you get the same result?

# (k) using the matrix() and sample.int() functions, insert missing values into mtcars and repeat.



# Problem 2: Strings and Dates -----------------------------------
# consider the following vector of fiscal years
y <- 1999:2017
fy <- paste(y - 1L, substr(as.character(y), 3L, 4L), sep = "/")

# (a) make sure you understand how these fiscal year strings were generated by looking up the relevant functions, e.g. ?substr

# (b) wrap this code into a function called FY(), that can create sequences of fiscal years from arbitrary starting and ending calendar years 

# (c) now create a function FY_to_Date() that takes a vector of fiscal years and converts it to a vector of Dates corresponding to the last day (30th of June) of each fiscal year

# (d) generate a vector of fiscal years and apply your function to turn them into dates. 

# (e) using substr(), get the month from these generated dates. 


# Problem 3: Basic Statistical Analysis using the Macro Data Portal --------------------------
# Open a browser and go to the Macro Data Portal Website: https://mepd.shinyapps.io/Macro-Data-Portal/
# The dataset shown is the total fiscal operations, Updated to October 2020
# Click on the 'Variables' tab, and examine the variables. This should look familiar to you from the GFS excel sheet.
# Look at the 'Class' column. Do you recognize the R type and in brackets behind the storage type of the variables?

# Now on your left where is says 'Select Variables', select all the time variables (Date-Month)
# and additionally the variables 'REV_TOT', 'REV_URA', 'REV_NON_URA', 'GRA_TOT'. Click 'Apply Selection'
# Go to the 'Summary' tab and briefly examine the statistics of the data.
# Now go to the plot window. What do you notice? Can you see the impact of COVID-19?
# On the top left you can click, on 'Joint' to see all series in one chart, then go back to 'Individual Series'. 
# We will look at this a bit more closely. Go back to the 'Table' tab and hit the 'Filter Data' checkbox.
# Click on the blue question mark and briefly comprehend the message. 
# Now you will only consider data since 2017. Type 'Year >= 2017' in the filter query box and hit 'Apply Filter'. 
# Go back to the 'Plot' tab. You should now only see data from 2017 in the plot. 
# To more clearly see the impact of COVID-19 on revenue, we will get rid of some seasonality in the plot. 
# On your left there is a checkbox called 'Transform Data'. Hit that checkbox. 
# In the field 'Data Transformations' scroll down until you find a filter called 'cubic spline trend (very soft)'.
# At the bottom hit the checkbox 'Add Transformed Variables' and click the 'Transform' button. 
# You should now see two lines in each chart, the original series in red and a smooth trend in green. 
# The trend can give you an idea of what the impact of COVID-19 on revenue could have been. 
# Now we will use this trend to seasonally adjust the data. Therefore click on 'cubic spline trend (very soft)'
# and remove it by hitting delete or backspace on your keyboard. Now scroll down all the way to the bottom of the
# list of filters and hit 'Seasonal adj. on cubic spline (very soft)'. 
# What this will do is subtract the smooth trend from the data, then regress the residuals on a series of monthly dummy
# variables, and add the residuals from the regression back to the smooth trend. 
# Examine this seasonally adjusted data: In which month was the greatest impact on URA revenue? (you may want to use the 'Table' tab to also look at the numbers.)

# Finally, we will aggregate this data to quarterly frequency and look at this again.
# To do this, first go back to the 'Table' tab. This data runs up to October 2020, which is part of the new quarter. 
# Let's remove this value by changing the filter query to 'Year >= 2017 & Date < "2020-10-01"'. 
# Now further down hit the 'Aggregate' checkbox. Select 'Year' and 'Quarter' (or alternatively 'FY' and 'QFY') as aggregator ID variables
# In the 'Aggregator Functions' box, remove the mean and select the sum. Then hit 'Aggregate'. 
# Go back to the 'Plot' window. In which Quarter of 2020 was the greatest revenue shortfall?. 

# Finally, you will download this data and open it in R. Go back to the 'Table' tab and at the bottom left of the page hit
# 'R' and then download. Your browser should then bring up a window where you can save of choose to open the file. 
# Click on 'Open with', and then search for 'Rstudio' as the program to open the file and hit OK. 
# Rstudio should now open and you will be requested to give a name to the dataset, the default being 'Overall Fiscal Operations'. 
# Change this to 'REV' and hit OK. You should now see the 'REV' dataset in your global environment, along with 
# a line of code printed in the console that imported your data. Click on 'REV' in the global environment to view the data in Rstudio.
# summarize the dat aby typing summary(REV) into the console.

# That's it, you survived the first session and homework assignment. We will be taking off from here and doing some analysis
# ourself in R after the next session. 



