#############################################################
# *************** R BASED DATA SCIENCE TRAINING *************
# Course 6: Computable Documents and Interactive Dashboards 
# -----------------------------------------------------------
# Prepared by: Sebastian Krantz, ODI Fellow, MEPD, MoFPED
# Permanent Contact: sebastian.krantz@graduateinstitute.ch
#############################################################

# Course Aim: To familiarize participants with computable documents in R via Rmarkdown,  
#             some basic Latex and HTML, interactive dashboards via flexdashboard,
#             and interactive data visualization with plotly.         


# This Course:
# (1) Intro to Rmarkdown and Computable Documents
# (2) Code Chunks, Data and Output Formats
# (3) Intro to Latex
# (4) Intro to HTML and CSS
# (5) Table making Packages in R (kable and kableExtra)
# (6) Interactive visualization wit plotly
# (7) Dashboards with flexdashboard
# (8) Case study: Make your own COVID-19 Dashboard

# Today: We'll try to cover topics 1-6.


setwd("Course 6 - Computable Documents and Interactive Dashboards in R")

# (1) Intro to Rmarkdown and Computable Documents --------------------------
#***************************************************************************

# https://rmarkdown.rstudio.com/index.html

# R Markdown documents are fully reproducible. Use a productive notebook interface to weave together narrative text 
# and code to produce elegantly formatted output.

# R Markdown supports dozens of static and dynamic output formats including HTML, PDF, MS Word, Beamer, HTML5 slides, 
# Tufte-style handouts, books, dashboards, shiny applications, scientific articles, websites, and more. 


# https://rmarkdown.rstudio.com/lesson-1.html

install.packages("rmarkdown")

### All you need to know to master Rmarkdown: 
# Cheatsheet: https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf
# Reference Guide: https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
# Online Book: Rmarkdown - The Definitive Guide: https://bookdown.org/yihui/rmarkdown/
# Another great online book (More details in some areas): https://bookdown.org/yihui/rmarkdown-cookbook/


# Now let's create out first Rmarkdown document 
# In Rstudio click File -> New File -> R Markdown

# Notice that the file contains three types of content:
  
# An (optional) YAML header surrounded by ---s
# R code chunks surrounded by ```s
# text mixed with simple text formatting

# When you open the file in the RStudio IDE, it becomes a notebook interface for R. You can run each code chunk by clicking the green arrow on the right. 
# RStudio executes the code and display the results inline with your file.


# To generate a report from the file, hit the 'knit' button at the top of the document in Rstudio,
# or run the render command:

library(rmarkdown)
render("test.Rmd")

# R Markdown generates a new file that contains selected text, code, and results from the .Rmd file. 
# The new file can be a finished web page, PDF, MS Word document, slide show, notebook, handout, book, dashboard, package vignette or other format

# When you run render, R Markdown feeds the .Rmd file to knitr, which executes all of the code chunks and creates a new markdown (.md) document which includes the code and its output.
# The markdown file generated by knitr is then processed by pandoc which is responsible for creating the finished format.
# This may sound complicated, but R Markdown makes it extremely simple by encapsulating all of the above processing into a single render function.


# Formats:
# https://rmarkdown.rstudio.com/formats.html


# (2) Code Chunks, Data and Output Formats ---------------------------------
#***************************************************************************

# You can quickly insert chunks into your file with

# - the keyboard shortcut Ctrl + Alt + I (OS X: Cmd + Option + I)
# - by typing the chunk delimiters ```{r} and ```.

# Chunk Options

# Chunk output can be customized with knitr options, arguments set in the {} of a chunk header. Above, we use five arguments:
  
# include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
# echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
# message = FALSE prevents messages that are generated by code from appearing in the finished file.
# warning = FALSE prevents warnings that are generated by code from appearing in the finished.
# fig.cap = "..." adds a caption to graphical results.

# See the R Markdown Reference Guide for a complete list of knitr chunk options.
# Global Options

# To set global options that apply to every chunk in your file, call knitr::opts_chunk$set in a code chunk. Knitr will treat each option that you pass to knitr::opts_chunk$set as a global default that can be overwritten in individual chunk headers.


#****************************
### In-Class Exercise 1 -----
#****************************

# (a) The time series matrix EuStockMarkets plots stock market indicators for the EU
plot(EuStockMarkets)
# Create an Rmarkdown file the shows both summary statistics and plots of the indicators

# (b) use the ugatsdb package to get the quarterly trade balance and current account balance 
# for uganda, create an automatic HTML report that displays both together in a chart created with
# ggplot2 or xts plot() and some brief commentary. 

# remotes::install_github('https://github.com/SebKrantz/UGATSDB', auth_token = paste0('ghp_PDwAszQN2T', 'n9nKaPnQUyrZPt7L3iPw3YQ7wh'))

library(ugatsdb)
ugatsdb_reconnect()
View(datasets())
View(series("BOU_BOP"))
bop_data <- get_data("BOU_BOP", c("CAB", "CA_G"))
help("ugatsdb")

library(xts)
bop_xts <- as.xts(bop_data)
plot(bop_xts, legend.loc = "topright", 
     main = "Current account and balance of trade",
     yaxis.right = FALSE)

library(dygraphs)
dygraph(bop_xts)


# Inline Code
# Code results can be inserted directly into the text of a .Rmd file by enclosing the code with `r `.

# R Markdown will always

# - display the results of inline code, but not the code
# - apply relevant text formatting to the results

# As a result, inline output is indistinguishable from the surrounding text. Inline expressions do not take knitr options.


# Other languages:
# knitr can execute code in many languages besides R. Some of the available language engines include:
  
# - Python
# - SQL
# - Bash
# - Rcpp
# - Stan
# - JavaScript
# - CSS

# To process a code chunk using an alternate language engine, replace the r at the start of your chunk declaration with the name of the language

# Output formats:
# https://rmarkdown.rstudio.com/lesson-9.html
# Each output format is implemented as a function in R. You can customize the output by passing arguments to the function as sub-values of the output field:
args(rmarkdown::html_document)
?rmarkdown::html_document


# (3) Introduction to Latex ------------------------------------------------
#***************************************************************************

# Latex is a mathematics typesetting
# program that is the standard for most professional
# mathematics writing. It is based on the typesetting program
# TEX created by Donald Knuth of Stanford University (his first
# version appeared in 1978). Leslie Lamport was responsible for
# creating LATEX a more user friendly version of TEX.

# Latex is used to write articles in most fields like economics and physics
# https://www.tau.ac.il/~yashiv/smets_wouters.pdf
# https://d1wqtxts1xzle7.cloudfront.net/47724262/Tracing_Value-Added_and_Double_Counting_20160802-7698-mc2a0o.pdf?1470142761=&response-content-disposition=inline%3B+filename%3DTracing_Value_added_and_Double_Counting.pdf&Expires=1624370902&Signature=foqugmjCLKGcTRYMHso~pMWAzwEFR4ExIWfO9crSBckx78Y9aFGY7ijZfWChwvl4JGpuG-JRugv50mtGraYI-6Eue~ELFqFfKsTtz0ESHIkCeDLEc0KkHlP-esrjLvoXF-ZuAMZx5GJS8jkstnfUAmbh5csiDsvnei88uOu1VzV37Jg6jpq0oUEwngu9HHSXTUenc1-4NJqIHAtzB1~Kv~EHZv1vw93~z80UNTo3PiZF9~BCw1QwMEl74rDDvq-QiPE1nGjbOl4s~AGzFKrVLI3i~J9BY5Yf81KGiYfKBiTH0dQxT07yt2fGO98lX859eqfuvjh-gkwSUt4FXhteQw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA
# https://reader.elsevier.com/reader/sd/pii/S037026931200857X?token=A404E1512325025B899315ADF9B79F496B77D443A1A7860006230A8A18D9FE1367E5F8BB6EB1137A87E3B29186BB1B98&originRegion=eu-west-1&originCreation=20210622131850

# Latex can be used to write beautiful and well-formatted papers, reports and presentations. 

# Online Latex Editing via
# https://www.overleaf.com/
# Also enables easy Online Share-Editing of Latex reports.
# Quick guide to latex provided by overleaf (also provided as PDF in the materials): # https://www.overleaf.com/latex/templates/a-quick-guide-to-latex/fghqpfgnxggz

# First, let's install latex:
# https://miktex.org/download

#****************************
### In-Class Exercise 2 -----
#****************************

# (a) Create a beamer presentation in Rmarkdown
#     using File -> Rmarkdown -> Presentation -> Beamer

# Lets get some key data on Uganda reflecting the recent pandemic
ugatsdb::ugatsdb_reconnect()
data <- ugatsdb::get_data("MOF_POE", c("CIEA", "BTI", "PMI", "EX", "IM", "TB"), from = 2019)
data_xts <- xts::as.xts(data)
library(collapse)
lab <- vlabels(data)

# This generates A table of summary statistics in latex
kableExtra::kbl(round(qsu(data, cols = -1, vlabels = TRUE), 2), format = "latex", 
                booktabs = TRUE, linesep = "")

# This generates some plots
plot(data_xts[, "CIEA"], col = "orange", main = lab["CIEA"])
plot(data_xts[, "BTI"], col = "darkgreen", main = lab["BTI"])
plot(data_xts[, "PMI"], col = "magenta", main = lab["PMI"])
plot(data_xts[, c("EX", "IM")], main = "Exports and Imports (US$ millions)", legend.loc = "topleft")
plot(data_xts[, "TB"], col = "red", main = lab["TB"])

# Add the table with statistics and the plot to the Rmarkdown beamer presentation. 
# If you have extra time add some brief commentary on the indicators.

# (b) Now re-implement the presentation using the latex beamer template. 
# to do that you need to save the charts as PDF using the plots pane or the dev.copy
# command introduced in course 2. 


# (3) Introduction to HTML and CSS ----------------------------------------
#**************************************************************************

# The HyperText Markup Language, or HTML is the standard markup language for documents designed to be displayed 
# in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages 
# such as JavaScript (https://en.wikipedia.org/wiki/HTML).

# Quick way to learn HTML, CSS and JavaScript and start web-development: Traversy Media on Youtube: 
# HTML Crashcourse: https://www.youtube.com/watch?v=UB1O30fR-EE&list=RDCMUC29ju8bIPH5as8OGnQzwJyA&index=3
# CSS Crashcourse:
# https://www.youtube.com/watch?v=yfoY53QXEnI&list=RDCMUC29ju8bIPH5as8OGnQzwJyA&start_radio=1
# https://www.youtube.com/watch?v=JJSoEo8JSnc&list=RDCMUC29ju8bIPH5as8OGnQzwJyA&index=4
# Built a HTML5 Website with a responsive layout: 
# https://www.youtube.com/watch?v=Wm6CUkswsNw&list=RDCMUC29ju8bIPH5as8OGnQzwJyA&index=8

# Another great, free and systematic resource is W3schools:
# Also: https://www.w3schools.com/html/

# You can write HTML in a plain text editor such as the windows editor, and display the page using a web-browser.
# For real web-development projects I recommend Sublime text Editor: https://www.sublimetext.com/
# which has syntax highlighting for many programming languages including HTML. 

# Another useful skill is to use the web-inspector of your browser to view and change some aspect of a website you browse. 
# For Example changing colours using any of these HTML colours: https://www.google.com/search?client=firefox-b-d&q=HTML+colour+picker

# In Firefox Browser, you can view the HTML source code of any website by hitting ctrl + u (on Windows), 
# Or putting "view-source:" in front of the web-address, e.g. view-source:https://finance.go.ug/


# (3) Tables in R -------------------------------------------------
#******************************************************************

# By default, R Markdown displays data frames and matrices as they would be in the R terminal (in a monospaced font). 
# If you prefer that data be displayed with additional formatting you can use the knitr::kable function, as in the .Rmd file below.
# Note the use of the results='asis' chunk option. This is required to ensure that the raw table output isn’t processed further by knitr.

# Examples of nice tabls with different R packages:
# https://rfortherestofus.com/2019/11/how-to-make-beautiful-tables-in-r/

# Huxtable Package + Comparisons with outher tables:
# https://cran.r-project.org/web/packages/huxtable/vignettes/design-principles.html
# Anoth overview:
# https://bookdown.org/yihui/rmarkdown-cookbook/table-other.html


# In this session we will use a package that is rather simple but suffices for 
# most practical purposes: The kableExtra pachage which extends the knitr::kable function
# Kable Extra: https://haozhu233.github.io/kableExtra/

# A nice general reasource for generatin Latex and HTML tables online is: https://www.tablesgenerator.com/latex_tables

#****************************
### In-Class Exercise 3 -----
#****************************

# (a) Using the readxl package, import the fiscal table of the computable POE example, 
# and print it to latex using the kableExtra package. Set up an Rmarkdown 
# Document that renders to Latex and includes the table.

library(readxl)
library(kableExtra)
fiscal <- read_excel("Computable POE/data/POE-other-data.xlsx")
 kbl(fiscal, format = "latex")

# (b) Paste the data in https://www.tablesgenerator.com/latex_tables and generate a Latex table.
# Paste that table into the Latex document template provided in the materials and render the document. 



# (8) Interactive visualization wit plotly ---------------------------------
#***************************************************************************

# R Markdown documents are a perfect platform for interactive content. 
# To make your documents interactive, add:
  
# Htmlwidgets are R functions that return JavaScript visualizations. 
# A number are summarized here http://www.htmlwidgets.org/
# Also: apexcharter, d3r. 

# Plotly is arguable the most flexible and commonly used interactive visualization library in the R community. 
# It as based on D3 - Data Driven Documents (https://d3js.org/), a very powerful JavaScript charting library 
# More at https://en.wikipedia.org/wiki/Plotly and https://plotly.com/

# For R the website and guidance is: https://plotly.com/r/
# Another Grat resource is the online book: https://plotly-r.com
# "Interactive web-based data visualization with R, plotly, and shiny"

# Lets plot some data for Uganda from collapse::wlddev datase
library(collapse)
library(magrittr) # Pipe operators
library(plotly)

wldug <- wlddev %>% fsubset(country == "Uganda") 

 plot_ly(wldug,
    x = ~ year,
    y = ~ PCGDP
  )

 plot_ly(wldug,
   x = ~ year,
   y = ~ PCGDP, 
   type = "scatter",
   mode = "markers+lines"
 )

  plot_ly(wldug,
    x = ~ year,
    y = ~ PCGDP, 
    type = "scatter",
    mode = "markers+lines", 
    name = "GDP per capita",
    hoverinfo = "x+y+name"
  ) %>% 
  layout(yaxis = list(title = "GDP per capita (constant 2010 US$)"), 
         hovermode = "compare")

# We can add a second variable using the add_trace function:
  
  plot_ly(wldug,
          x = ~ year,
          y = ~ PCGDP, 
          type = "scatter",
          mode = "markers+lines", 
          name = "GDP per capita",
          hoverinfo = "x+y+name"
  ) %>% 
    add_trace(y = ~ LIFEEX, 
              name = "Life Expectancy") %>%
    layout(yaxis = list(title = "Value"), 
           hovermode = "compare")
  
# This however does not make a lot of sense, as the variable are on different scales
# We could put them on different scales:

  plot_ly(wldug,
          x = ~ year,
          y = ~ PCGDP, 
          type = "scatter",
          mode = "markers+lines", 
          name = "GDP per capita",
          hoverinfo = "x+y+name"
  ) %>% 
    add_trace(y = ~ LIFEEX, 
              name = "Life Expectancy", 
              yaxis = "y2") %>%
    layout(title = "GDP Per Capita and Life Expectancy in Uganda, 1960-2017",
           yaxis = list(title = "GDP per capita (constant 2010 US$)", 
                        tickformat = "$",
                        hoverformat = '$.1f'), 
           yaxis2 = list(
             overlaying = "y",
             side = "right",
             title = "Life expectancy at birth, total (years)",
             hoverformat = '.2f'
           ),
           xaxis = list(title = "Year", showgrid = FALSE),
           hovermode = "compare", 
           legend = list(x = 0.04, y = 0.95), 
           margin = list(
             l = 60, r = 60,
             b = 40, t = 40,
             pad = 2
           ))
# Here I also added some margins to the plot, positioned the legend, and 
# formatted the y-axis and the hoverinfo. More about D3 formatting here: https://github.com/d3/d3-format
  
# Ok, so we successfully created a pretty fancy interactive chart of GDP per capita and Life Expectancy in Uganda
# More about line plots here: https://plotly.com/r/line-charts/
  
# Now let's look at some other charts. 
# For example we could generate a chart of Kenyan Employment by Sector:
library(data.table) # Needed for melt() function
EMPKEN <- GGDC10S %>% 
          fsubset(Country == "KEN" & Variable == "EMP", -SUM) %>% 
          qDT %>% melt(1:5, na.rm = TRUE)

range(EMPKEN$Year)

# Line chart with hover mode "x unify"  
plot_ly(EMPKEN, 
        x = ~ Year,
        y = ~ value,
        color = ~ variable, 
        colors = rainbow(10),
        type = 'scatter', 
        mode = 'lines') %>%
  layout(title = "Kenyan Employment by Sector, 1969-2011",
         yaxis = list(title = "Employment in Thousands", 
                      hoverformat = '.2s'), 
         hovermode = "x unified")

# Line chart with hover mode "x unify"  
plot_ly(EMPKEN, 
        x = ~ Year,
        y = ~ value,
        color = ~ variable, 
        colors = rainbow(10),
        type = 'scatter', 
        mode = 'none', 
        fill = TRUE,
        stackgroup = 'one', 
        groupnorm = 'fraction') %>%
  layout(title = "Kenyan Employment by Sector, 1969-2011", 
         yaxis = list(title = "Employment Share in Percent", 
                      range = c(0, 1),
                      dtick = 0.1,
                      tickformat = "%",
                      hoverformat = '.2%'), 
         xaxis = list(showgrid = FALSE),
         hovermode = "x unified", 
         hoverlabel = list(bgcolor = 'rgba(255, 255, 255, 0.8)',
                           bordercolor = "transparent"), 
         margin = list(pad = 3))

# Further links
# https://plotly.com/r/plotly-fundamentals/ (fundamentals about axes etc.)

# More Systematic: 
# https://plotly.com/r/reference/index/
# -> a simple example of a plotly chart inlined with links to each attribute's reference section. 

# For example: All layout properties are documented at: https://plotly.com/r/reference/#layout




# Miscellaneous Other topics: -----------------------------------------

# Markdown language: 
# https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html

# Other Presentation Formats: 
# https://rmarkdown.rstudio.com/lesson-11.html
# Overleaf
# https://www.r-bloggers.com/2019/09/mastering-r-presentations/

# Rmarkdown Websites: 
# https://rmarkdown.rstudio.com/lesson-13.html
# https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html


# A nice Rmarkdown template that renders to both HTML and Latex:
remotes::install_github("grantmcdermott/lecturenotes")

# You can also use my computable POE template provided (apart from the cover Page)